seed: 42
file_path: /home/lwoudstr/scratch/GIFFLAR/data_pret/expanded_glycans.txt
logs_dir: /home/lwoudstr/scratch/GIFFLAR/logs_pret
pre-transforms:
  GIFFLARTransform:
  GNNGLYTransform:
  ECFPTransform:
  SweetNetTransform:
  RGCNTransform:
  PyTorchRGCNTransform:
  MonosaccharidePrediction:
    mode: both
transforms:
  - name: TypeMasking
    cell: atoms
    prob: 0.15
  - name: TypeMasking
    cell: bonds
    prob: 0.15
model:
  name: gifflar
  feat_dim: 128
  hidden_dim: 1024
  batch_size: 64
  num_layers: 8
  epochs: 150
  learning_rate: 0.001
  optimizer: Adam
  loss: dynamic
  suffix: _exp
